### ISSUE TITLE
React Router 4

### ISSUE THREAD

**Issue by msimonc** [mcdermed/Elkwood#1]
Can you update to React Router 4?  Thanks

**Comment by mcdermed** [comment]
Yeah I'd love to. I haven't had the time to use it in any of my current projects, so it could be some time until I get to doing the upgrade. If you're looking to learn React Router 4 with these examples, eventually I'll find some time to update the project.

Since putting together this example, I am inspired by the work done on https://github.com/zeit/next.js/. Though it uses it's own custom router with static routes, I think it is an elegant solution to route specific chunking. It's also a better solution if you are looking for an out of the box framework for many of the principles I was trying to achieve with this example.

**Comment by mcdermed** [comment]
I'm not going to upgrade `react-router` to `v4` as dynamic routing has been descoped. 
https://github.com/mcdermed/Elkwood/commit/79274797a1f12b0a980a92995eaf22f76280fc35

There are a couple approaches to this problem discussed here https://github.com/ReactTraining/react-router/issues/3968
